# Generated by Django 4.1.1 on 2022-09-30 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hec_backend', '0002_alter_signosvitales_presion_arterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signosvitales',
            name='fecha_muestra',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
