# Generated by Django 4.1.1 on 2022-10-01 23:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hec_backend', '0004_alter_sugerenciascuidado_fecha_sugerencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='fecha_diagnostico',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
